- name: Link .tmux.conf
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/.tmux.conf"
    dest: "{{ home_dir }}/.tmux.conf"
    state: link
    force: true

- name: Check if TPM directory exists
  stat:
    path: "{{ home_dir }}/.tmux/plugins/tpm"
  register: tpm_dir

- name: Install TPM
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ home_dir }}/.tmux/plugins/tpm"
    update: true
  when: not tpm_dir.stat.exists
