; https://huggingface.co/blog/ggml-org/model-management-in-llamacpp

version = 1

[*]
threads = 8
parallel = 1
flash-attn = on
jinja = true
mlock = off
mmap = off
fit = off
; warmup = off
batch-size = 4096
ubatch-size = 512
cache-type-k = q4_0
cache-type-v = q8_0
cache-prompt = true
cache-reuse = 256
cache-ram = 32768
ctx-size = 16384

[unsloth/gemma-4-26B-A4B-it-GGUF]
hf-repo = unsloth/gemma-4-26B-A4B-it-GGUF:UD-IQ4_XS
ctx-size = 32768
temp = 1.0
top-p = 0.95
top-k = 64
